name: Dispatch

on:
  issues:
    types: 
      - opened

jobs:
  parse-issue-title:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.parse-title.outputs.result }}
    steps:
      - name: Parse issue title
        id: parse-title
        uses: actions/github-script@v6
        with:
          env: 
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = "${{ github.event.issue.number }}";
            const issueTitle = "${{ github.event.issue.title }}".toLowerCase();
            return issueTitle;
          result-encoding: string